name: Stage sequenziali

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scrivi-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scrivi file
        run: |
          echo "Ciao, sono il primo job!" > file.txt
          echo "File scritto con successo!"

      - name: Upload artefatto
        uses: actions/upload-artifact@v4
        with:
          name: generated-file
          path: file.txt

  leggi-file:
    needs: scrivi-file
    runs-on: ubuntu-latest

    steps:
      - name: Download artefatto
        uses: actions/download-artifact@v4
        with:
          name: generated-file

      - name: Verifica esistenza file
        run: |
          if [ -f "file.txt" ]; then
            echo "Il file esiste!"
          else
            echo "Il file non esiste!"
            exit 1
          fi

      - name: Lettura del file
        run: |
          cat file.txt